image: docker:19.03.13
variables:
  DOCKER_DRIVER: overlay
stages:
  - build
build:
  stage: build
  image: docker:19.03.13
  variables:
    IMAGE_NAME: "ity-mqtt-gateway"
    CONTAINER_REGISTRY: "cr.yandex/crpvmu6t1sbqt5cor7n1"
    PACKAGE_VERSION: $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  services:
    - name: docker:19.03.13-dind
  script:
    - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - docker login cr.yandex
    - docker build -f Dockerfile.prod -t $IMAGE_NAME:latest  .
    - docker tag $IMAGE_NAME:latest $CONTAINER_REGISTRY/$IMAGE_NAME:latest
    - docker tag $IMAGE_NAME:latest $CONTAINER_REGISTRY/$IMAGE_NAME:$PACKAGE_VERSION
    - docker push $CONTAINER_REGISTRY/$IMAGE_NAME:latest
    - docker push $CONTAINER_REGISTRY/$IMAGE_NAME:$PACKAGE_VERSION
    - docker rmi $IMAGE_NAME:latest $CONTAINER_REGISTRY/$IMAGE_NAME:latest
