FROM node:16.17.0-buster as build
WORKDIR /usr/src/app/
COPY package.json .
COPY package-lock.json .
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production
#RUN node-prune

FROM node:16.17.0-buster-slim
WORKDIR /usr/src/app/
COPY --from=build /usr/src/app/package.json ./package.json
COPY --from=build /usr/src/app/package-lock.json ./package-lock.json
COPY --from=build /usr/src/app/node_modules/ ./node_modules/
COPY --from=build /usr/src/app/dist/ ./dist/
CMD npm run start